### ISSUE TITLE
Error in Wang 2016 derived DD5 calculation. 

### ISSUE THREAD

**Issue by see24** [bcgov/cmip6-BC-eval#6]
I noticed that you have the derived variables from Wang 2016 in your repo and I wanted to give you a heads up that I found an issue in that paper when I implemented those functions in R a couple years ago. 
I emailed Tongli about it and he agreed the paper was wrong.

First of all in the paper the DD5 equation looks like this:
 
![dd5](https://user-images.githubusercontent.com/39161074/137031204-6ea0583f-e46b-4973-a2fd-ce27fdec017d.png)
I believe the directions of the > and < are reversed because it should be a straight line at temperatures above k and a curve heading to zero below k.

Secondly, when I calculated DD5 using the parameters in the paper the DD5 was higher than it should be for many locations. When I investigated the issue I found that a graph made using the parameters in the paper did not match the graph for DD5 vs Jan mean temperature in the paper (see graph below left, blue line). I discovered that if I exchanged the parameters b and T0 from the S2 Table the graph appeared to match the paper (see graphs below red lines, and table below).
  
![dd5_2](https://user-images.githubusercontent.com/39161074/137031246-00ae01d0-92bb-4579-b18e-e1cc3b7c1167.png)
![dd5_3](https://user-images.githubusercontent.com/39161074/137031255-afec0da9-ac7a-4abf-97cd-396237d51f7b.png)
![dd5_4](https://user-images.githubusercontent.com/39161074/137031264-5d5bccc6-0489-456b-8ab5-21c6cc57ccda.png)

Also if you haven't coded the equations yet I might be able to share my code but would have to check with my employer so let me know if you are interested!

BTW cool app! And thanks for making the code available

**Comment by cmahony** [comment]
Thanks for letting us know! we fixed this in climr and i notified Tongli, who i believe had already fixed it. much appreciated.
